version: "3"

services:
    node-test:
        image: node:lts-bookworm-slim
        container_name: node-test
        restart: on-failure

        working_dir: /app

        volumes:
            - ./:/app

        command: sh -c "cd .. && ls"

        networks:
            - proxy_net

networks:
    proxy_net:
        external: true
