version: "3"

services:
    node-test:
        build: .
        container_name: test-api
        restart: on-failure
        networks:
            - proxy_net

networks:
    proxy_net:
        external: true
